name: flutter_animation_pro_8sc
description: Animated login with Rive
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # Si tu .riv está en assets/, descomenta:
  # assets:
  #   - assets/animated_login_character.riv
